### ISSUE TITLE
R-ecology lesson 04 visualization

### ISSUE THREAD

**Issue by gorgievad** [datacarpentry/R-ecology-lesson#717]
Hello,
on the website for the 4th lesson on R ecology visualization, aka https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html , on the areas where there are Challenges and answers for them (accordion buttons that are supposed to drop down with text when you click on them), the answers are not showing up for me for any of the challenges on that page. This error only occurs on that one page, the fourth lesson. I would really like to double check my answers with the correct ones (yours) so please can you fix this or send me the correct answers?
Thank you in advance.

**Comment by fmichonneau** [comment]
Thanks for bringing this up to our attention. It should be fixed now.

**Comment by DrMaggie** [comment]
Hi, I'm still experiencing issues with the solutions to https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html#Challenges (the violin & box plots) not being accessible - there is no clickable "button".
I use the latest version of Chrome for Windows 10 (Version 90.0.4430.93 (Official Build) (64-bit)).
